import cart1 from '@/assets/cart-1.png'
import cart2 from '@/assets/cart-2.png'
import cart3 from '@/assets/cart-3.png'
import cart4 from '@/assets/cart-4.png'
import cart5 from '@/assets/cart-5.png'
import cart6 from '@/assets/cart-6.png'


const Products = [
  {
    id: 1,
    name: "Shiny Dress",
    image: cart1,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 95.50,
    info: "Almost Sold Out",
    category: "Women’s Fashion",
  },
  {
    id: 2,
    name: "Long Dress",
    image: cart2,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 45.00,
    info: "Sold Out",
    category: "Women’s Fashion",
  },
  {
    id: 3,
    name: "Full Sweater",
    image: cart3,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 89.99,
    info: "Almost Sold Out",
    category: "Women’s Fashion",
  },
  {
    id: 4,
    name: "White Dress",
    image: cart4,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 39.99,
    info: "Almost Sold Out",
    category: "Women’s Fashion",
  },
  {
    id: 5,
    name: "Colorful Dress",
    image: cart5,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 29.99,
    info: "Sold Out",
    category: "Women’s Fashion",
  },
  {
    id: 6,
    name: "White Shirt",
    image: cart6,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 49.99,
    info: "Almost Sold Out",
    category: "Women’s Fashion",
  },
  // {
  //   id: 7,
  //   name: "Casual Shirt",
  //   image: cart7,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 35.99,
  //   info: "Almost Sold Out",
  //   category: "Men’s Fashion",
  // },
  // {
  //   id: 8,
  //   name: "Denim Jacket",
  //   image: cart8,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 59.99,
  //   info: "Sold Out",
  //   category: "Men’s Fashion",
  // },
  // {
  //   id: 9,
  //   name: "Formal Suit",
  //   image: cart9,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 99.99,
  //   info: "Almost Sold Out",
  //   category: "Men’s Fashion",
  // },
  // {
  //   id: 10,
  //   name: "Polo T-Shirt",
  //   image: cart10,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 29.99,
  //   info: "Almost Sold Out",
  //   category: "Men’s Fashion",
  // },
  // {
  //   id: 11,
  //   name: "Black Hoodie",
  //   image: cart11,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 44.99,
  //   info: "Sold Out",
  //   category: "Men’s Fashion",
  // },
  // {
  //   id: 12,
  //   name: "Slim Fit Jeans",
  //   image: cart12,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 54.99,
  //   info: "Almost Sold Out",
  //   category: "Men’s Fashion",
  // },
//   {
//   id: 13,
//   name: "Leather Handbag",
//   image: cart13,
//   brand: "Gucci",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 65.99,
//   info: "Almost Sold Out",
//   category: "Women Accessories",
// },
// {
//   id: 14,
//   name: "Gold Necklace",
//   image: cart14,
//   brand: "Pandora",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 89.99,
//   info: "Sold Out",
//   category: "Women Accessories",
// },
// {
//   id: 15,
//   name: "Stylish Sunglasses",
//   image: cart15,
//   brand: "Ray-Ban",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 49.99,
//   info: "Almost Sold Out",
//   category: "Women Accessories",
// },
// {
//   id: 16,
//   name: "Luxury Watch",
//   image: cart16,
//   brand: "Fossil",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 120.99,
//   info: "Almost Sold Out",
//   category: "Women Accessories",
// },
// {
//   id: 17,
//   name: "Silver Earrings",
//   image: cart17,
//   brand: "Pandora",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 35.99,
//   info: "Sold Out",
//   category: "Women Accessories",
// },
// {
//   id: 18,
//   name: "Fashion Belt",
//   image: cart18,
//   brand: "Michael Kors",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 29.99,
//   info: "Almost Sold Out",
//   category: "Women Accessories",
// },
// {
//   id: 19,
//   name: "Leather Wallet",
//   image: cart19,
//   brand: "Tommy Hilfiger",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 34.99,
//   info: "Almost Sold Out",
//   category: "Men Accessories",
// },
// {
//   id: 20,
//   name: "Classic Watch",
//   image: cart20,
//   brand: "Casio",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 79.99,
//   info: "Sold Out",
//   category: "Men Accessories",
// },
// {
//   id: 21,
//   name: "Black Sunglasses",
//   image: cart21,
//   brand: "Ray-Ban",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 54.99,
//   info: "Almost Sold Out",
//   category: "Men Accessories",
// },
// {
//   id: 22,
//   name: "Winter Jacket",
//   image: cart22,
//   brand: "Zara",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 49.99,
//   info: "50% OFF",
//   category: "Discount Deals",
// },
// {
//   id: 23,
//   name: "Running Shoes",
//   image: cart23,
//   brand: "Nike",
//   rating: "(4.1k) Customer Reviews",
//   stars: 5,
//   price: 39.99,
//   info: "40% OFF",
//   category: "Discount Deals",
// },
];

export default Products ;