import cart1 from '@/assets/cart-1.png'
import cart2 from '@/assets/cart-2.png'
import cart3 from '@/assets/cart-3.png'
import cart4 from '@/assets/cart-4.png'
import cart5 from '@/assets/cart-5.png'
import cart6 from '@/assets/cart-6.png'


const Products = [
  {
    id: 1,
    name: "Shiny Dress",
    image: cart1,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 95.50,
    info: "Almost Sold Out",
    category: "Women’s Fashion",
  },
  {
    id: 2,
    name: "Long Dress",
    image: cart2,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 45.00,
    info: "Sold Out",
    category: "Women’s Fashion",
  },
  {
    id: 3,
    name: "Full Sweater",
    image: cart3,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 89.99,
    info: "Almost Sold Out",
    category: "Women’s Fashion",
  },
  {
    id: 4,
    name: "White Dress",
    image: cart4,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 39.99,
    info: "Almost Sold Out",
    category: "Women’s Fashion",
  },
  {
    id: 5,
    name: "Colorful Dress",
    image: cart5,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 29.99,
    info: "Sold Out",
    category: "Women’s Fashion",
  },
  {
    id: 6,
    name: "White Shirt",
    image: cart6,
    brand: "Al Karam",
    rating: "(4.1k) Customer Reviews",
    stars: 5,
    price: 49.99,
    info: "Almost Sold Out",
    category: "Women’s Fashion",
  },
  // {
  //   id: 7,
  //   name: "Casual Shirt",
  //   image: cart7,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 35.99,
  //   info: "Almost Sold Out",
  //   category: "Men’s Fashion",
  // },
  // {
  //   id: 8,
  //   name: "Denim Jacket",
  //   image: cart8,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 59.99,
  //   info: "Sold Out",
  //   category: "Men’s Fashion",
  // },
  // {
  //   id: 9,
  //   name: "Formal Suit",
  //   image: cart9,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 99.99,
  //   info: "Almost Sold Out",
  //   category: "Men’s Fashion",
  // },
  // {
  //   id: 10,
  //   name: "Polo T-Shirt",
  //   image: cart10,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 29.99,
  //   info: "Almost Sold Out",
  //   category: "Men’s Fashion",
  // },
  // {
  //   id: 11,
  //   name: "Black Hoodie",
  //   image: cart11,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 44.99,
  //   info: "Sold Out",
  //   category: "Men’s Fashion",
  // },
  // {
  //   id: 12,
  //   name: "Slim Fit Jeans",
  //   image: cart12,
  //   brand: "Levis",
  //   rating: "(4.1k) Customer Reviews",
  //   stars: 5,
  //   price: 54.99,
  //   info: "Almost Sold Out",
  //   category: "Men’s Fashion",
  // },
];

export default Products ;