import { Poppins, Volkhov } from "next/font/google";
import "./globals.css";

const volkhov = Volkhov({
  variable: "--font-volkhov",
  weight: ["400","700"],
});

const poppins = Poppins({
   variable: "--font-poppins",
   weight: ["400","500","600", "800","700"],
});

export const metadata = {
  title: "Fasco",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${volkhov.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
